#!/usr/bin/env node

'use strict';

const axios = require('axios');
const winston = require('winston');
const path = require('path');
winston.loggers.add('cmdstubs',{
    transports: [
        new winston.transports.Console({
            level: 'debug',
            label: 'cmdstubs',
            colorize: 'true'
        })
    ]
});

let logger = winston.loggers.get('cmdstubs');
let cmd = path.parse(__filename).name;
logger.info('running stub for ',cmd);

let api = `http://localhost:3000/${cmd}/`;
let data = process.argv.slice(2);
logger.info(api,data);
axios.post(api, {
    cmd,
    data
})
    .then( (response)=>{
        let rc = response.data.exitcode;
        //logger.info(response.data.stdout);
        //logger.info(response.data.stderr);
        process.exit(rc);
    }).catch( (err)=>{
        logger.error(err);
        process.exit(1138);
    });